# -*- coding: utf-8 -*-
"""texttovideo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEmZGHA0sLpRF8y0kEQugot6uMC_8gZ3
"""

!pip install diffusers transformers accelerate torch

import torch
from diffusers import DiffusionPipeline, DPMSolverMultistepScheduler
from diffusers.utils import export_to_video

pipe = DiffusionPipeline.from_pretrained("damo-vilab/text-to-video-ms-1.7b", torch_dtype=torch.float16, variant="fp16")
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()

prompt = "a kid celebrating his birthday"
video_frames = pipe(prompt, num_inference_steps=25).frames
video_frames = video_frames.reshape((-1, *video_frames.shape[-3:]))
video_path = export_to_video(video_frames)